sshkeygen improvements + dependecies

diff --git a/agent_Dockerfile b/agent_Dockerfile
--- a/agent_Dockerfile
+++ b/agent_Dockerfile
@@ -7,13 +7,33 @@ ENV JENKINS_AGENT_HOME=/var/jenkins_home
 
 ## Install docker on the agent
 RUN  curl -sSL https://get.docker.com/ | sh
-## PHP + rsync for blt/robo, make to run commands from Makefile, composer to install deps, vim because is great :).
+
+## PHP
 RUN apt-get update \
     && apt-get -y --no-install-recommends install \
-    php-cli \
+    php-cli
+
+## Composer.
+RUN EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)" && \
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
+    ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")" && \
+    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; \
+        then >&2 echo 'ERROR: Invalid installer checksum' ; \
+        rm composer-setup.php; exit 1; \ 
+    fi && \
+    php composer-setup.php --quiet && \
+    rm composer-setup.php && \
+    mv composer.phar /usr/local/bin/composer && \    
+    chmod +x /usr/local/bin/composer && \
+    ls -l /usr/local/bin/
+
+## PHP + rsync for blt/robo, make to run commands from Makefile, vim because is great :).
+RUN apt-get update \
+    && apt-get -y --no-install-recommends install \
     php-xml \
+    php-curl \
+    php-mbstring \
     build-essential \
-    composer \
     rsync \
     vim \
     && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
